---
version: "3"
services:
  mpiler:
    image: cghub/mailpiler
    container_name: mpiler
    hostname: mpiler.yourdomain.com
    environment:
      - PILER_HOST=mpiler.yourdomain.com
      - MYSQL_PILER_PASSWORD=${MYSQL_PILER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /opt/piler/data:/var/piler
      - /opt/piler/conf:/etc/piler
      - /opt/mysql/data:/var/lib/mysql
    ports:
      - "25:25"
      - "80:80" 
    restart: always
