---
version: "3"
services:
  mpiler:
    image: cghub/mailpiler
    container_name: mpiler
    hostname: mpiler
    environment:
      - PILER_HOST=mpiler.yourdomain.com
    volumes:
      - /var/piler:/var/piler
    ports:
      - "25:25"
      - "80:80" 
    restart: always
