---
version: "3"
services:
  mpiler:
    image: cghub/mpiler
    container_name: mpiler
    hostname: mpiler
    environment:
      - PILER_HOST=mpiler.yourdomain.com
    volumes:
      - /var/piler:/var/piler
      - /var/mysql:/var/lib/mysql
    ports:
      - 25:25
      - 80:80 #optional
    restart: always
