---
version: "3"
services:
  mpiler:
    image: cghub/mailpiler
    container_name: mpiler
    hostname: mpiler.demo.cybergate.lk
    environment:
      - PILER_HOST=mpiler.demo.cybergate.lk
      - MYSQL_PILER_PASSWORD=${MYSQL_PILER_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - piler_data:/var/piler
      - piler_conf:/etc/piler
      - mysql_data:/var/lib/mysql
    ports:
      - "25:25"
      - "80:80"
    restart: always
volumes:
  piler_data:
  piler_conf:
  mysql_data:

