PACKAGE="piler_1.3.7-bionic-94c54a0_amd64.deb"
DEBIAN_FRONTEND="noninteractive"
DISTRO="bionic"
DOWNLOAD_URL="https://download.mailpiler.com"
PILER_USER="piler"
MYSQL_HOSTNAME="localhost"
MYSQL_DATABASE="piler"
MYSQL_PILER_PASSWORD=$(openssl rand -base64 8)
MYSQL_ROOT_PASSWORD=$(openssl rand -base64 8)
SPHINX_BIN_TARGZ="sphinx-3.1.1-bin.tar.gz"
cat << EOF > ./.env
PACKAGE=${PACKAGE}
DEBIAN_FRONTEND=${DEBIAN_FRONTEND}
DISTRO=${DISTRO}
DOWNLOAD_URL=${DOWNLOAD_URL}
PILER_USER=${PILER_USER}
MYSQL_HOSTNAME=${MYSQL_HOSTNAME}
MYSQL_DATABASE=${MYSQL_DATABASE}
MYSQL_PILER_PASSWORD=${MYSQL_PILER_PASSWORD}
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
SPHINX_BIN_TARGZ=${SPHINX_BIN_TARGZ}
EOF
